...

diff --git a/bin/pairup b/bin/pairup
--- a/bin/pairup
+++ b/bin/pairup
@@ -35,8 +35,12 @@ function terse_time {
 }
 
 function do_create {
+    if [[ -z "$1" ]]; then
+        echo 'PairUp! session name required.'
+        exit 1
+    fi
     assert_conf $PAIRUP_CONF
-    SESSION=${1:-$PAIRUP_SESSION}
+    SESSION=$1
     terse_time stackato push $SESSION -n
     echo
     echo Now you are ready to:
@@ -54,7 +58,7 @@ function do_conf {
         cat <<EOS
 You need a $PAIRUP_CONF file like:
 
-    confs/default-pairup-conf.sh
+    confs/pairup-conf.sh
 
 EOS
         while [[ -z "$conf" ]]; do
@@ -172,7 +176,7 @@ function assert_conf {
     local conf=${1:-$PAIRUP_APP/$PAIRUP_CONF}
     if [[ ! -f $conf ]]; then
         format_as_error "No '$conf' file. Cannot continue."
-        echo "Try something like: " `format_as_cmd "$0 conf confs/default-pairup-conf.sh"`
+        echo "Try something like: " `format_as_cmd "$0 conf confs/pairup-conf.sh"`
         exit 1
     fi
     source $conf
